### POST Greeting
POST http://localhost:8080/
Content-Type: application/json

{
    "userId": "kido001",
    "userName": "KIDO BAE",
    "age": 40
}

### GET user
GET http://localhost:8080/users/hello
Content-Type: application/json

### GET user
GET http://localhost:8080/users/ex/hello
Content-Type: application/json